config/routes.rb
Rails.application.routes.draw do
  root "q_generators#index"
  devise_for :users

  resources :q_generators
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/q_generator.rb
class QGenerator < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :q_generators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/q_generators_controller.rb
class QGeneratorsController < ApplicationController
  before_action :set_q_generator, only: [:show, :edit, :update]

  def index
    @q_generators = current_user.q_generators.all
    @quote_count = @q_generators.count 
    if @quote_count == 0
      @q_generators = generate_quotes(current_user)
      @quote_count = @q_generators.count 
    end


  end

  def show
  end

  def new
    @q_generator= q_generator.new
  end

  def create
    @q_generator = current_user.q_generators.new(q_generator_params)

    if @q_generator.save
      redirect_to q_generators_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @q_generator.update(q_generator_params)
      redirect_to q_generators_path
    else
      render :edit
    end
  end

  def destroy
    @q_generator.destroy
    redirect_to q_generators_path
  end

  private

  def q_generator_params
  params.require(:q_generator).permit(:name, :message)
  end

  def set_q_generator
    return @q_generator = QGenerator.find(params[:id])   if params[:id].to_i >= 1
  end

  def generate_quotes(current_user)
    25.times do
      QGenerator.create(
          message: Faker::MichaelScott.quote,
          user_id: current_user.id
        )
    end
    QGenerator.find_by(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/q_generators_helper.rb
module QGeneratorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/q_generators/edit.html.erb
<h1>QGenerators#edit</h1>
<p>Find me in app/views/q_generators/edit.html.erb</p>

app/views/q_generators/index.html.erb
<h1><%= current_user.first_name %>! Enjoy Some Q</h1>
<hr />
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<br />
<br />

<% @q_generators.each do |q|%>
  <p><%=q.message%></p>
  <%end%>
  <%= link_to "Generate A Quote", q_generator_path(rand(@quote_count)) %>

app/views/q_generators/new.html.erb
<h1>QGenerators#new</h1>
<p>Find me in app/views/q_generators/new.html.erb</p>

app/views/q_generators/show.html.erb
<%= @q_generator&.message || "No Quotes" %>